[package]
# build = "build.rs"
name = "ludo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.0"
sdl2-sys = "0.35.0"
ash = "0.37.3"
